version: '3.8'

services:
  django:
    build: .
    container_name: ghjk34_django
    expose:
      - 8000
    volumes:
      - static_data:/var/www/ghjk34/staticfiles
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: ghjk34_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env.docker
  
  nginx:
    image: nginx:1.25
    container_name: ghjk34_nginx
    ports:
      - 80:80
    depends_on:
      - django
    volumes:
      - static_data:/var/www/ghjk34/staticfiles
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  pg_data:
  static_data:
