# Generated by Django 4.2.3 on 2023-07-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=49, verbose_name='Название')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
            ],
        ),
    ]
